### PR TITLE
Code Restructure - if you like it

### PR DESCRIPTION
**Pull request by ryanmobley**
I was messing around with ways to rewrite some of this code better, and yeah I ended up going all in. I think I improved the structure of the code and made it more clear. I didn't modify any functionalities. The application should work exactly as it did previously, and I tested the updated code and noticed no issues.

What I changed:

- I redid the `Assets` class and removed the assets object and any function arguments that used it. Now, everything in the class is used statically. `Assets.initAssets()` is called in main. I also removed `InteractableKind`. Anything that uses the `kind` variable in an `Interactable` now just handles it as a plain string.

- The big thing: I turned `Interactable` into an 'abstract class', and the Interactables are now objects of subclasses: `LogicGate`, `Input`, and `Timer`. Basically, I left the code that applied to all three types in `Interactable` and split any functions with if/else into individual functions in the subclasses. I added `swapGate()` and `alternate()` functions to replace the prevs/nexts/nots from `InteractableKind`. Hope you don't hate me for all the lambda functions to calculate the `LogicGate` states. :)

- I changed file interactions to the nice syntax, `with open(...) as`, which automatically closes the file after.

Feel free to accept some or all of these modifications if you feel that they improve the code for you or anyone else to work on it in the future. Regardless, this was a good challenge in OOP for me.

### CODE REVIEW

**Comment by SteveBenz** [comment]
Hey thanks!  I'll have a look at it this weekend or next week.  Work this week has used up my entire allotment of context-switches for the month.  Definitely like the subclassing of Interactable.  In addition to the 'draw' code, we should probably find a way to make the rules surrounding attaching connections a part of the subclasses.  (E.g. timers can only take one input, buttons can't have any inputs).  I rather liked InteractableKind, but maybe I've not entirely gotten into the Python groove.

It also seems to me that there's a huge performance win to be had if we could be more intelligent about drawing the screen, but perhaps a pro-pygamer would know better.  If there is such a win to be had, I'm sure the code will be a whole lot better in a subclass like this.

**Comment by ryanmobley** [comment]
Good point about the inputs, yep. I think you're right about the drawing performance. I definitely noticed more lag with a lot of interactables and arrows on the screen, and I have to assume that's from every loop redrawing them. I've never used pygame, so I left all pygame functionalities as they were. ¯\_(ツ)_/¯ Probably wouldn't be tooooo hard to cut down on the redrawing, though...?

I'm also pretty busy at the moment (coming up on finals), so that might be all I'm doing on this. If I do make any more changes, though, I'll be sure to add them here or make another pull request.

**Comment by SteveBenz** [comment]
I let myself get sucked into this today.  I just took your changes and added on more in the same vein.

**Comment by SteveBenz** [comment]
I got to looking about that comment you made about the 10-tick timer not being accurate.  You're right.  But after some experimentation, I've convinced myself that it is a correctly implementing what Scrap Mechanic would call a 9-tick timer.

I suspect we're in wild agreement about this, but I'll go ahead and push on with the reason why it's working correctly as a 9-tick timer.  The lynchpin of the proof is the behavior of the Scrap Mechanic "0 tick" timer.  Which we both know actually imposes a 1 tick delay.  If you send a one-tick pulse through a series of 0-tick timers, it behaves like a series of AND gates - lighting up in sequence.  Screenshots of a one-tick pulse flowing through a series of 0-tick timers always seem to come up showing a single timer lit up.

In the simulator, there's nothing wonky about how the lights come on, and I'm pretty sure if I hacked the array size from 10 to 1 it'd behave exactly like the game.

So I think I have a documentation bug - I need to fix the readme.  In Scrap Mechanic, an n-tick timer really imposes an n+1 tick delay.

**Pull request merged**
